syntax on

filetype indent plugin on

let mapleader = "\<Space>"
let loaded_matchparen = 1 " disable math parenthiese

nnoremap ; :
nnoremap 0 ^

set number
set ruler
set scrolloff=10

set noswapfile
set backspace=indent,eol,start
set clipboard=unnamed
set iskeyword+=-

set ignorecase
set smartcase
set incsearch
set hlsearch

set foldmethod=indent
set foldlevel=99

set autoindent
set smartindent
set copyindent
set cindent

set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

autocmd FileType html,xml,yaml,css,scss,javascript setlocal shiftwidth=2 softtabstop=2 tabstop=2 expandtab
autocmd FileType c          setlocal shiftwidth=8 softtabstop=8 tabstop=8 noexpandtab

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" YouCompleteMe is a fast, as-you-type, fuzzy-search code completion engine for Vim.
Plugin 'ycm-core/YouCompleteMe'

Plugin 'morhetz/gruvbox'

call vundle#end()

colorscheme gruvbox
set background=dark
