
call plug#begin()

" A small sensible Vim configuration
Plug 'tpope/vim-sensible'

" A code-completion engine for Vim
Plug 'ycm-core/YouCompleteMe', { 'do': './install.py' }

" Retro groove color scheme for Vim 
Plug 'morhetz/gruvbox'

" Initialize plugin system
call plug#end()

silent! colorscheme gruvbox
set background=dark

